name: Feature Request
description: "Request a feature."
body:
  - type: markdown
    attributes:
      value: "Please use this form to request features. We ask you check if it was already requested though"
  - type: input
    id: discord
    attributes:
      label: Your GTNH Discord Username
      description: Leave empty if you don't have one, but this will make it harder to contact you if we need additional info.
      placeholder: "Example: Wumpus#1234"
  - type: textarea
    id: request
    attributes:
      label: Feature Request
      description: "Relevant information, as well as relevant images"
      placeholder: "Example: https://mclo.gs/ OR submit the file to github by dragging it to this textbox."
    validations:
      required: true
  - type: checkboxes
    id: final
    attributes:
      label: Final Checklist
      description: Certify that you read things
      options:
        - label: "I have searched the issues and haven't found a similar issue."
          required: true
