on:
    push:
        branches:
            - master
name: Wiki Sync
jobs:
    update-wiki:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Sync Wiki
            uses: GTNewHorizons/ghaction-wiki-sync@master
            with:
                username: "GitHub-GTNH-Actions"
                access_token: ${{ secrets.GITHUB_TOKEN }}
                ignore_safe_warnings: true
                commit_username: "GitHub GTNH Actions"
                commit_email: "<>"
                commit_message: "automatic wiki sync: ${{ github.event.commits[0].message }}"
